config/routes.rb
Rails.application.routes.draw do
  get "/"            => 'static_pages#home'
  get  '/signup'     => 'salons#new'
  post  '/signup'    => 'salons#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'  
  resources :salons
  resources :users
  resources :products
  resources :purchases
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
validates :brand, presence: true
validates :number, presence: true
validates :name, presence: true
validates :term, presence: true
has_many :purchases, foreign_key: :product_number
has_many :users, through: :purchases
belongs_to :salon
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user, optional: true, foreign_key: :user_number
    belongs_to :product, optional: true, foreign_key: :product_number
    belongs_to :salon
end

app/models/salon.rb
class Salon < ApplicationRecord
  has_many :products
  has_many :users
  has_many :purchases


  attr_accessor :remember_token  
  before_save { self.email=email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true 

  def Salon.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  def Salon.new_token
    SecureRandom.urlsafe_base64
  end
  def remember
    self.remember_token = Salon.new_token
    update_attribute(:remember_digest, Salon.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end  

end

app/models/user.rb
class User < ApplicationRecord    
validates :name, presence: true, length: { maximum: 50 }
validates :number, presence: true
has_many :purchases, foreign_key: :user_number
has_many :products, through: :purchases
belongs_to :salon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
    before_action :set_current_salon
  
  def set_current_salon
    @current_salon = Salon.find_by(id: session[:salon_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products=Product.where(salon_id: current_salon.id)
    @product=Product.new
  end

  def create
    @product = Product.new(product_params.merge(salon_id: current_salon.id))
    if @product.save
      flash[:success] = "Success!"
      redirect_to "/products"
    else
      redirect_to "/products"
    end
  end
  
  def edit
      @product=Product.find(params[:id])
  end
  
  def update
      product=Product.find(params[:id])
      product.update(product_params)
      redirect_to "/products"
  end 
  
  def destroy
     Product.find(params[:id]).destroy
    flash[:success] = "deleted"
    redirect_to "/products"
  end
  
   private
     def product_params
      params.require(:product).permit(:number, :brand, :name, :term)
     end  
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.where(salon_id: current_salon.id)
    @purchase = Purchase.new
  end

  def create
    @purchase= Purchase.new(purchase_params.merge(salon_id: current_salon.id))
    if @purchase.save
      flash[:success] = "Success!"
      redirect_to "/purchases"
    else
      redirect_to "/purchases"
    end
  end

  def edit
      @purchase=Purchase.find(params[:id])
  end

  def update
      purchase=Purchase.find(params[:id])
      purchase.update(purchase_params)
      redirect_to "/purchases"
  end 

  def destroy
     Purchase.find(params[:id]).destroy
    flash[:success]= "deleted"
    redirect_to "/purchases"
  end

   private

     def purchase_params
      params.require(:purchase).permit(:user_number, :product_number)
     end  
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :logged_in_salon, only: [:edit, :update]  
  before_action :correct_user,   only: [:edit, :update]
  def show
    @salon = Salon.find(params[:id])
  end
 
  def new
    @salon = Salon.new
  end

  def create
    @salon = Salon.new(salon_params)   
    if @salon.save
       log_in @salon
      flash[:success] = "Welcome!"
      redirect_to "/"
    else
      redirect_to "/"
    end
  end
  
  def edit
    @salon = Salon.find(params[:id])
  end
  
  def update
    @salon = Salon.find(params[:id])
    if @salon.update_attributes(salon_params)
      flash[:success] = "Profile updated"
      redirect_to "/top"
    else
      render 'edit'
    end
  end  
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
  
  private

    def salon_params
      params.require(:salon).permit(:name, :email, :password,
                                   :password_confirmation)  
    end
   
    def logged_in_salon
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_salon
      @salon = Salon.find(params[:id])
      redirect_to(root_url) unless current_salon?(@salon)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    salon = Salon.find_by(email: params[:session][:email].downcase)
    if salon && salon.authenticate(params[:session][:password])
      log_in salon
      params[:session][:remember_me] == '1' ? remember(salon) : forget(salon)
       redirect_to "/"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to '/'
    end
  end

  def destroy
    log_out
    redirect_to "/"    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where(salon_id: current_salon.id)
    @user= User.new
  end


  def create
    @user= User.new(user_params.merge(salon_id: current_salon.id))
    if @user.save
      flash[:notice] = "Success!"
      redirect_to "/users"
    else
      redirect_to "/users"
    end
  end
  
  def edit
      @user=User.find(params[:id])
  end
  
  def update
      user=User.find(params[:id])
      user.update(user_params)
      redirect_to "/users"
  end   

  def destroy
     User.find(params[:id]).destroy
    flash[:success] = "deleted"
    redirect_to "/users"
  end  
  
   private
   
     def user_params
      params.require(:user).permit(:number, :name, :email)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(salon)
    session[:salon_id] = salon.id
  end

  def remember(salon)
    salon.remember
    cookies.permanent.signed[:salon_id] = salon.id
    cookies.permanent[:remember_token] = salon.remember_token
  end

  def current_salon?(salon)
    salon == current_salon
  end

  def current_salon
    if (salon_id = session[:salon_id])
      @current_salon ||= Salon.find_by(id: salon_id)
    elsif (salon_id = cookies.signed[:salon_id])
      salon = Salon.find_by(id: salon_id)
      if salon && salon.authenticated?(cookies[:remember_token])
        log_in salon
        @current_salon = salon
      end
    end
  end
  
  def logged_in?
    !current_salon.nil?
  end
  
  def log_out
    session.delete(:salon_id)
    @current_salon = nil
  end  
  # 永続的セッションを破棄する
  def forget(salon)
    salon.forget
    cookies.delete(:salon_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_salon)
    session.delete(:salon_id)
    @current_salon = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Repeat Alert", '/', id:"logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
        
           <% if logged_in? %>
            <li><%= link_to "アラート一覧",   '/purchases' %></li>
            <li><%= link_to "登録商品一覧",   '/products' %></li>
              <li><%= link_to "お客様一覧", '/users' %></li>
              <li><%= link_to "Profile", current_salon %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "signup", '/signup'%></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Update product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>

      <%= f.label :brand %>
      <%= f.select :brand, [["ReFa", "ReFa"], ["PLOSION", "PLOSION"], ["SIXPAD", "SIXPAD"], ["MDNA SKIN", "MDNA SKIN"]], include_blank: "選択して下さい" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :term %>
      <%= f.select :term, [["10日", "10"], ["20日", "20"], ["30日", "30"], ["40日", "40"], ["50日", "50"], ["60日", "60"]], include_blank: "選択して下さい" %>

      <%= f.submit "商品マスター変更", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="product_index">
<h1>登録商品一覧</h1>
    <table class="table">
    <thead>
        <tr>
         　 <th>No.</th>
         　 <th>ブランド</th>
        　  <th>商品名</th>
        　  <th>使用期間</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody>
            <% @products.each do |product| %>
        <tr>
            <td><%= product.number %></td>
            <td><%= product.brand %></td>
            <td><%= product.name %></td>
            <td> <%= product.term %></td>
            <td><%= link_to "編集", "/products/#{product.id}/edit", class:"btn btn-primary mr-3" %></td>
            <td><%= link_to "削除", product, method: :delete, class:"btn btn-primary mr-3" %></td>
            
            <% end %>
        </tr>
    </tbody>
</table>
</div>

<div class="product_form">
  <h2>商品マスター登録はこちら</h2>
    <%= form_for(@product, url: "/products") do |f| %>
      <%= f.label :number %>
      <%= f.number_field :number, class: 'form-control' %>
      <%= f.label :brand %>
      <%= f.select :brand, [["ReFa", "ReFa"], ["PLOSION", "PLOSION"], ["SIXPAD", "SIXPAD"], ["MDNA SKIN", "MDNA SKIN"]], include_blank: "選択して下さい" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :term %>
      <%= f.select :term, [["10日", "10"], ["20日", "20"], ["30日", "30"], ["40日", "40"], ["50日", "50"], ["60日", "60"]], include_blank: "選択して下さい" %>

      <%= f.submit "商品マスター登録", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/purchases/index.html.erb
<div class="purchase_index">
<h1>購入商品一覧</h1>
        <table class="table">
            <thead>
                <tr>
                 　 <th>お客様No.</th>
                　  <th>お客様名</th>
                　  <th>ブランド</th>
                 　 <th>商品名</th>
                　  <th>購入日</th>
                　  <th>残り日数</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                    <% @purchases.each do |purchase| %>
                <tr>
                    <td><%= purchase.user_number %></td>
                    <td><%= purchase.user.name %></td>
                    <td><%= purchase.product.brand %></td>
                    <td><%= purchase.product.name %></td>
                    <td><%= purchase.created_at.strftime('%Y/%m/%d')  %></td>
                    <td><%= purchase.product.term - (Date.today - purchase.created_at.to_date).to_i %></td>　
                    <td><%= purchase.user.email %></td>
                    <td><%= link_to "削除", purchase, method: :delete, class:"btn btn-primary mr-3" %></td>
                    <% end %>
                <tr>
             </tbody>
        </table>      
</div>
<div class="purchase_form">
<h2>購入情報登録</h2>
    <%= form_for(@purchase) do |f| %>
      <%= f.label :user_number %>
      <%= f.number_field :user_number, class: 'form-control' %>
      <%= f.label :product_number %>
      <%= f.number_field :product_number, class: 'form-control' %>

      <%= f.submit "購入情報登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/salons/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@salon) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/salons/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@salon, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "サロン名" %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email, "Eメールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード(6文字以上必須)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/salons/show.html.erb
<%= @salon.name %>, <%= @salon.email %>
<h1>ログインサロン情報確認</h1>

app/views/static_pages/home.html.erb
<div class="section1">
    <div>
        <h1>
        簡単操作で<br>
        商品リピート購入率UP
        </h1>
    </div>
</div>
<div class="row">
</div>

app/views/users/edit.html.erb
<h1>Update user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :number %>
      <%= f.number_field :number, class: 'form-control' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="user_index">
<h1>お客様一覧</h1>
 <table class="table">
    <thead>
        <tr>
         　 <th>お客様No.</th>
        　  <th>お客様名</th>
        　  <th>E-mail</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody>
            <% @users.each do |user| %>
        <tr>
            <td><%= user.number %> </td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "編集", "/users/#{user.id}/edit", class:"btn btn-primary mr-3" %></td>
            <td><%= link_to "削除", user, method: :delete, class:"btn btn-primary mr-3" %></td>
            <% end %>
        </tr>
    </tbody>
</table>
</div>

<div class="user_form">
<h2>お客様マスター情報登録はこちら</h2>
    <%= form_for(@user, url:"/users")do |f| %>
      <%= f.label :number %>
      <%= f.number_field :number, class: 'form-control' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
</div>